### ISSUE TITLE
Fix Colexio Manuel Peleteiro 

### ISSUE THREAD

**Issue by jsanz** [geoinquietosvlc/antipodes-map#40]
Message by @fdansv from CartoDB:

> School Name: Colexio Manuel Peleteiro 
> School Direction: Lugar do Monte Redondo, 15702 Santiago de Compostela, A Coruña 
> School Coordinates: 42.8550084,-8.5377886 
> 
> La localización que tenéis en el mapa, en el centro de Santiago, fue cerrada hace unos 6 años, y lleva unos cuatro abandonada, tras ser brevemente usada como comisaría de policía. Detallo arriba los nuevos datos.

**Comment by vehrka** [comment]
Hola Francisco (@fdansv),

Muchas gracias por el aviso, ya hemos actualizado la dirección y las coordenadas.

Ah, y ¡Feliz año!

Un saludo,

**Comment by fdansv** [comment]
Gracias, y buena suerte con el proyecto, me parece muy interesante!
